version: '3'
services:
  
  geoserver-basemaps:
    image: 'geotekne/geoserver:lime-alpine-2.16.2'
    hostname: geoserver-basemaps
    env_file:
      - ./geoserver.env
    ports:
      - "8080:8080"
    volumes:
      - './data/geoserver/data_dir_basemaps/:/var/local/geoserver'
    depends_on:
      - geoserver-osm-transparent
      - geoserver-osm-opaque
      - geoserver-satellite
    restart: on-failure

  geoserver-osm-transparent:
    image: 'geotekne/geoserver:lime-alpine-2.16.2'
    hostname: geoserver-osm-transparent
    ports:
      - "8081:8080"
    env_file:
      - ./geoserver.env
    volumes:
      - './data/geoserver/data_dir_osm_transparent/:/var/local/geoserver'
      - './data/geoserver/gpkg/:/var/local/geoserver/data'
    depends_on:
      - postgis-osm
    restart: on-failure

  geoserver-osm-opaque:
    image: 'geotekne/geoserver:lime-alpine-2.16.2'
    hostname: geoserver-osm-opaque
    ports: 
      - "8082:8080"
    env_file:
      - ./geoserver.env
    volumes:
      - './data/geoserver/data_dir_osm_opaque/:/var/local/geoserver'
      - './data/geoserver/gpkg/:/var/local/geoserver/data'
    depends_on:
      - postgis-osm
    restart: on-failure

  geoserver-satellite:
    image: 'geotekne/geoserver:pear-alpine-2.16.2'
    hostname: geoserver-satellite
    ports:
      - "8083:8080"
    env_file:
      - ./geoserver.env
    volumes:
      - './data/geoserver/data_dir_satellite/:/var/local/geoserver'
    restart: on-failure

  wmsclient:
    image: 'nginx:1.21.3-alpine'
    hostname: wmsclient
    volumes:
      - './data/nginx/html:/usr/share/nginx/html'
    ports:
      - "80:80"
    restart: on-failure

  postgis-osm:
    image: 'kartoza/postgis:12.1'
    hostname: postgis
    container_name: all-basemaps-geoserver_postgis
    env_file:
      - ./postgis.env
    volumes:
      - 'pgdata:/var/lib/postgresql'
    ports:
      - "5432:5432"
    restart: on-failure

  imposm-worker:
    image: 'geotekne/imposm-worker:1.0.0'
    hostname: imposm-worker
    environment:
      - PARAMETERS=-i /pbfs -c all-basemaps-geoserver_postgis -v 12.1 -p 5432 -u docker -w docker -d gis
    volumes:
      - './pbfs/:/pbfs'
    depends_on:
      - postgis-osm

volumes: 
     pgdata:

